<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2kGP1X\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2kGP1X/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF2kGP1X.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF2kGP1X\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerF2kGP1X\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'F2kGP1X',
    'container.build_id' => '8fc6233f',
    'container.build_time' => 1524909975,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2kGP1X');
